
INCLUDE += -I$(SYNC_TOP_SRC)/include/base/
INCLUDE += -I$(SYNC_TOP_SRC)/include/sync/

default = $(PROG)

C_FLAGS += $(INCLUDE) -Wall -Werror

.c.o:
	gcc -c $< $(C_FLAGS)

$(PROG):$(PROG_OBJ)
	gcc -o $(PROG) $(PROG_OBJ) $(C_FLAGS) -L$(SYNC_TOP_SRC)/lib/ $(LIB) $(EXT_LIB)
	cp $(PROG) $(SYNC_TOP_SRC)/installing/bin/

clean:
	@rm -rf *.o
	@rm -rf $(PROG)

install:
	cp $(PROG) $(SYNC_TOP_SRC)/installing/bin/
	

