
subdirs:
	@set -e;for n in $(SUBDIRS); \
	do  \
		$(MAKE) -C $$n || exit 1 ;  \
	done


clean:
	@set -e;for n in $(SUBDIRS);\
	do \
	$(MAKE) -C $$n clean || exit 1; \
	done

install:
	@set -e;for n in $(SUBDIRS); \
	do  \
	$(MAKE) -C $$n install|| exit 1 ;  \
	done
